# Generated by Django 2.0.1 on 2018-07-28 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20180728_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plants',
            old_name='phase',
            new_name='flowering',
        ),
        migrations.RenameField(
            model_name='plants',
            old_name='parts',
            new_name='medicinal_parts',
        ),
    ]
