# Generated by Django 2.0.1 on 2018-07-25 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20180723_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='add_time',
            field=models.DateField(default=datetime.datetime(2018, 7, 25, 11, 7, 57, 924793), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='plants',
            name='add_time',
            field=models.DateField(default=datetime.datetime(2018, 7, 25, 11, 7, 57, 925793), verbose_name='添加时间'),
        ),
    ]
