# Generated by Django 2.0.1 on 2018-07-28 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '收藏信息',
                'verbose_name': '收藏信息',
                'db_table': 'favorite',
            },
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateField(verbose_name='开始时间')),
                ('end', models.DateField(verbose_name='结束时间')),
                ('deliver_type', models.CharField(choices=[('client', '客户负责'), ('server', '服务员上门')], default='client', max_length=10, verbose_name='快递方式')),
                ('plant_type', models.CharField(choices=[('small', '小型'), ('middle', '中型'), ('large', '大型')], default='small', max_length=10, verbose_name='盆栽类型')),
                ('address', models.CharField(max_length=50, verbose_name='地址')),
                ('price', models.FloatField(max_length=20, verbose_name='代种价格')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '代种信息',
                'verbose_name': '代种信息',
                'db_table': 'generation',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='数量')),
                ('total_money', models.FloatField(max_length=100, verbose_name='金额')),
                ('state', models.IntegerField(choices=[(1, '已支付'), (2, '已发货'), (3, '运输中'), (4, '已到站'), (5, '已提货')], default=1, max_length=1, verbose_name='购买状态')),
                ('address', models.CharField(max_length=50, verbose_name='收货地址')),
                ('mobile', models.CharField(max_length=11, verbose_name='联系电话')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '购买信息',
                'verbose_name': '购买信息',
                'db_table': 'purchase',
            },
        ),
    ]
