# Generated by Django 2.0.1 on 2018-07-13 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
        ('operation', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='custom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Goods', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='generation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='顾客'),
        ),
        migrations.AddField(
            model_name='generation',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Staff', verbose_name='代种员工'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Goods', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
