# Generated by Django 2.0.1 on 2018-07-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20180728_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='state',
            field=models.IntegerField(choices=[(1, '已支付'), (2, '已发货'), (3, '运输中'), (4, '已到站'), (5, '已提货')], default=1, verbose_name='购买状态'),
        ),
    ]
