# Generated by Django 2.0.1 on 2018-07-13 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20180713_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='custom',
            new_name='customer',
        ),
    ]
