# Generated by Django 2.0.1 on 2018-07-29 10:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0004_auto_20180728_1602'),
        ('operation', '0003_auto_20180728_1121'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together={('customer', 'goods')},
        ),
    ]
