# Generated by Django 2.0.1 on 2018-07-29 10:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0004_auto_20180728_1602'),
        ('operation', '0004_auto_20180729_1036'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'good')},
        ),
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together=set(),
        ),
    ]
