# Generated by Django 2.0.1 on 2018-07-29 11:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20180728_1602'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0005_auto_20180729_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='user',
            new_name='customer',
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('customer', 'good')},
        ),
    ]
