# Generated by Django 2.0.1 on 2018-07-14 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.News', verbose_name='新闻标题'),
        ),
    ]
